#数据库相关配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rac_management?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&noAccessToProcedureBodies=true
    username: root
    password: 123456
    max-idle: 10
    max-wait: 10000
    min-idle: 10
    initial-size: 10
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    defaultPropertyInclusion: NON_EMPTY
    deserialization:
      fail_on_unknown_properties: false
  application:
    name: rac-management
  redis:
    host: 127.0.0.1
    port: 6379
rac:
  bizLineId: 1
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  url:
    login: http://localhost:8081/#/login
    logout: http://localhost:8081/#/logout
    success: http://localhost:8082/#/
  port: 8081
  servlet:
    context-path: /rac
dubbo:
  protocol:
    name: dubbo
    port: 12345
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
